
[package]
name = "eclipse"
version = "0.0.0"
edition = "2021"

rust-version = "1.95"
description = "Open-source Rust runtime for running the Android x86-64 Roblox client on Linux"
license = "MIT"
publish = false

[dependencies]

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "6"

zip = { version = "8", default-features = false, features = ["deflate"] }
sha2 = "0.11"

crc32fast = "1"

httpdate = "1.0.3"

libloading = "0.9"
jni-sys = "0.4"
jni = "0.22"

winit = { version = "0.30", default-features = false, features = ["rwh_06", "x11", "wayland", "wayland-dlopen", "wayland-csd-adwaita-crossfont"] }

rustix = { version = "1", default-features = false, features = ["mm", "param"] }

libc = "0.2"

ash = { version = "0.38", default-features = false, features = ["loaded", "std", "debug"] }
ash-window = "0.13"
raw-window-handle = "0.6"

khronos-egl = { version = "6", features = ["dynamic"] }

freetype-rs = "0.36"

cpal = "0.18"

tiny-skia = { version = "0.12", default-features = false, features = ["std", "simd"] }

libsqlite3-sys = { version = "0.38.1", features = ["bundled"] }

ureq = { version = "3.3.0", default-features = false, features = ["rustls"] }

[build-dependencies]

cc = "1"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unreachable_pub = "warn"
unused = { level = "warn", priority = -1 }

[lints.clippy]
all = { level = "warn", priority = -1 }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

panic = "abort"
strip = true
