
[package]
name = "eclipse-libm-shim"
version = "0.0.0"
edition = "2021"
publish = false
description = "apkenv-loadable, clean-relocation libm.so providing correct math from the pure-Rust libm crate"

[lib]
name = "eclipse_libm_shim"
crate-type = ["cdylib"]

[dependencies]

libm = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
panic = "abort"
